### ISSUE TITLE
Is it possible to send FCM push without notification tag

### ISSUE THREAD

**Issue by salini11** [saikatdutta1991/FirebaseCloudMessaging#2]
Now its sending both data and notification tag to the Apps. Is it possible to avoid notification tag since if it contains notification tag the OS is handling the Push not by the App.

**Comment by saikatdutta1991** [comment]
I did not try without notification tag. I think, when app is in background os will take care to show push notification by parsing the notification tag. So if you don't send the notification tag and app is in background, os will fail to show push notification. I have used  this library before and it works fine with notification and data tag. Because notification tag can only contain few parameters. You can hack this library you if you want.. I suggest you better to use another firebase push notification libarary. This 
 library i developed for learning purpose and only for my use and i am not maintaining this library anymore.
